#!/bin/bash

echo "test"
echo "test" 
echo "test" 
echo "test" 
echo "test" 
echo "test"

echo "test" 
echo "test" 
echo "test""

echo "test"
echo "test" 
echo "test" 
echo "test" 
echo "test" 
echo "test"

echo "test" 
echo "test" 
echo "test" 
echo "test"
echo "test" 
echo "test" 
echo "test" 
echo "test" 
echo "test"

echo "test" 
echo "test" 
echo "test" 


echo "test" 

echo "Test"
echo "1"
echo "2" 









